- name: make working directory
  become: yes
  file:
    path: /home/ec2-user/redmine-docker
    state: directory
    owner: ec2-user
    group: ec2-user

- name: make nginx directory
  become: yes
  file:
    path: /home/ec2-user/redmine-docker/nginx/conf
    state: directory
    owner: ec2-user
    group: ec2-user

- name: copy docker-compose.yml
  become: yes
  template:
    src: template/docker-compose.yml
    dest: /home/ec2-user/redmine-docker
    owner: ec2-user
    group: ec2-user

- name: copy nginx.conf
  become: yes
  template:
    src: template/nginx.conf
    dest: /home/ec2-user/redmine-docker/nginx/conf/
    owner: ec2-user
    group: ec2-user

- name: container up
  become: yes
  command: docker-compose up -d
  args:
    chdir: /home/ec2-user/redmine-docker/